import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
const Footer = () => {
    return (_jsx("footer", { className: "footer", children: _jsxs("div", { className: "footer-content", children: [_jsxs("div", { className: "footer-links", children: [_jsx(Link, { to: "/team", children: "Meet The Team" }), _jsx(Link, { to: "/aboutus", children: "About MunchMap" }), _jsx(Link, { to: "/contactus", children: "Contact Us" }), _jsx(Link, { to: "/privacy", children: "Privacy" })] }), _jsxs("div", { className: "footer-social", children: [_jsx("a", { href: "https://twitter.com", className: "social-link", children: _jsx("i", { className: "fab fa-twitter" }) }), _jsx("a", { href: "https://linkedin.com", className: "social-link", children: _jsx("i", { className: "fab fa-linkedin" }) }), _jsx("a", { href: "https://facebook.com", className: "social-link", children: _jsx("i", { className: "fab fa-facebook" }) })] })] }) }));
};
export const Privacy = () => {
    return (_jsxs("div", { style: { padding: '20px', fontFamily: 'Arial, sans-serif' }, children: [_jsx("h1", { children: "Privacy Policy" }), _jsx("p", { children: "Your privacy is important to us. This privacy policy explains how we collect, use, and protect your information." }), _jsx("h2", { children: "Information We Collect" }), _jsx("p", { children: "We may collect personal information such as your name, email address, and other details you provide when using our services." }), _jsx("h2", { children: "How We Use Your Information" }), _jsx("p", { children: "We use your information to provide and improve our services, communicate with you, and ensure a better user experience." }), _jsx("h2", { children: "Sharing Your Information" }), _jsx("p", { children: "We do not share your personal information with third parties except as required by law or to provide our services." }), _jsx("h2", { children: "Your Choices" }), _jsx("p", { children: "You can choose not to provide certain information, but this may limit your ability to use some features of our services." }), _jsx("h2", { children: "Contact Us" }), _jsx("p", { children: "If you have any questions about this privacy policy, please contact us at support@example.com." })] }));
};
export default Footer;
